name: CI

# These trigger patterns courtesy of https://github.com/broccolijs/broccoli/pull/436
on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - 'release-1.x'
      - 'v*'
    # always run CI for tags
    tags:
      - '*'

env:
  CI: true

jobs:
  test-locked-deps:
    name: Locked Deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test:ember
